apiVersion: v1
kind: Service
metadata:
  name: questnutri-admin-panel-service
spec:
  selector:
    app: questnutri-admin-panel-deployment
  type: LoadBalancer
  loadBalancerIP: 192.168.0.200
  ports:
    - port: 14041
      targetPort: 80
      protocol: TCP
      name: http