apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger-deployment
  labels:
    app: jaeger-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger-deployment
  template:
    metadata:
      labels:
        app: jaeger-deployment
    spec:
      containers:
        - name: jaeger
          image: jaegertracing/all-in-one:1.57
          ports:
            - containerPort: 16686
            - containerPort: 4317
            - containerPort: 4318
          env:
            - name: COLLECTOR_OTLP_ENABLED
              value: "true"
            - name: COLLECTOR_OTLP_HTTP_PORT
              value: "4318"
            - name: COLLECTOR_OTLP_GRPC_PORT
              value: "4317"
            - name: LOG_LEVEL
              value: "debug"
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-service
spec:
  type: LoadBalancer
  selector:
    app: jaeger-deployment
  loadBalancerIP: 192.168.0.210
  ports:
    - name: ui
      port: 16686
      targetPort: 16686
    - name: otlp-grpc
      port: 4317
      targetPort: 4317
    - name: otlp-http
      port: 4318
      targetPort: 4318
