apiVersion: apps/v1
kind: Deployment
metadata:
  name: questnutri-frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: questnutri-frontend-deployment
  template:
    metadata:
      labels:
        app: questnutri-frontend-deployment
    spec:
      containers:
        - name: frontend
          image: "questnutri/frontend-evolved:1.1.0"
          imagePullPolicy: Always
          ports:
            - containerPort: 80