apiVersion: v1
kind: Service
metadata:
  name: questnutri-frontend-service
spec:
  selector:
    app: questnutri-frontend-deployment
  type: LoadBalancer
  loadBalancerIP: 192.168.0.201
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http